server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Food Delivery App
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, /menus/**, /consolidatedOrderStatuses/**
        - id: Restaurant
          uri: http://localhost:8082
          predicates:
            - Path=/orderManagements/**, /orderDetailsViews/**
        - id: Payment
          uri: http://localhost:8083
          predicates:
            - Path=/paymentHistories/**, 
        - id: Customer
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Food Delivery App
          uri: http://foodDeliveryApp:8080
          predicates:
            - Path=/orders/**, /menus/**, /consolidatedOrderStatuses/**
        - id: Restaurant
          uri: http://restaurant:8080
          predicates:
            - Path=/orderManagements/**, /orderDetailsViews/**
        - id: Payment
          uri: http://payment:8080
          predicates:
            - Path=/paymentHistories/**, 
        - id: Customer
          uri: http://customer:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
