---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Food Delivery App
  labels:
    app: Food Delivery App
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Food Delivery App
  template:
    metadata:
      labels:
        app: Food Delivery App
    spec:
      containers:
        - name: Food Delivery App
          image: username/Food Delivery App:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Restaurant
  labels:
    app: Restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Restaurant
  template:
    metadata:
      labels:
        app: Restaurant
    spec:
      containers:
        - name: Restaurant
          image: username/Restaurant:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Payment
  labels:
    app: Payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Payment
  template:
    metadata:
      labels:
        app: Payment
    spec:
      containers:
        - name: Payment
          image: username/Payment:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Customer
  labels:
    app: Customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Customer
  template:
    metadata:
      labels:
        app: Customer
    spec:
      containers:
        - name: Customer
          image: username/Customer:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Food Delivery App
  labels:
    app: Food Delivery App
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Food Delivery App


---


apiVersion: v1
kind: Service
metadata:
  name: Restaurant
  labels:
    app: Restaurant
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Restaurant


---


apiVersion: v1
kind: Service
metadata:
  name: Payment
  labels:
    app: Payment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Payment


---


apiVersion: v1
kind: Service
metadata:
  name: Customer
  labels:
    app: Customer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Customer

